run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 1

storage:
  postgres:
    postgres_db:
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      hostname:
        env: POSTGRES_HOST
      db_name:
        env: POSTGRES_DB
      port: 5432

run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    image: voz-user-code:latest
    networks:
      - dev_voz_net
    env_vars:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - VOZ_THREAD_URL
      - HTTP_TIMEOUT_SECONDS
      - HTTP_DELAY_SECONDS
      - FLARESOLVERR_URL

telemetry:
  enabled: false
